$schema: https://railway.app/json-schema/railway-config.json

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    port: 3000
    environment:
      NODE_ENV: production

  mail-service:
    build:
      context: ./server/mail_service
      dockerfile: Dockerfile
    port: 3001
    environment:
      PORT: 3001
